apiVersion: v1
kind: Service
metadata:
  name: my-client
  labels:
    app: my-client
spec:
  type: NodePort
  selector:
    app: my-client
    version: v1
  ports:
    - name: client-tcp
      port: 3000
      protocol: TCP
